### ISSUE TITLE
Add Portuguese Names and Surnames

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/full-name-generator#14]
The repository is missing **Portuguese names and surnames**. Follow the guide below to add them.

## 🚀 How to Contribute:

1. **Fork** the repository.
2. **Add** names and surnames for your country following the format provided below.
3. **Submit** a Pull Request with your changes.
4. Please **include a reliable source** for the names and surnames you're adding, preferably a public database or a reputable website.

## 📄 Format:

For names (`src/names/pt.ts`):

```typescript
const portugueseNames = {
    0: [ // Male names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ],
    1: [ // Female names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ]
}

export default portugueseNames;
```

For surnames (`src/surnames/pt.ts`):

```typescript
const portugueseSurnames = [ // Add the URL of the surnames source here
    'Surname1', 'Surname2', 'Surname3', ...
];

export default portugueseSurnames;
```

## 📌 Important Notes:

- Ensure that the names and surnames you add are common and not specific to a small group.
- 50 names for both males and females, and 50 surnames.
- Organize the names with 10 entries per row.
- Avoid adding names that might be offensive or inappropriate.
- Ensure you're not violating any copyright or data privacy rules.

**Comment by aryankshl** [comment]
hey @ozdemirburak can you assign this to me?

**Comment by Ryan-Biondo** [comment]
I'm adding common, non-offensive Portuguese names/surnames sourced from FamilyEducation, Behind the Name, Surnam.es, Forebears, INE, and RNPN for cross-referencing.

**Comment by ozdemirburak** [comment]
Thanks, @Ryan-Biondo.
