### ISSUE TITLE
Add Chinese Names and Surnames

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/full-name-generator#4]
The repository is missing **Chinese names and surnames**. Follow the guide below to add them.

## 🚀 How to Contribute:

1. **Fork** the repository.
2. **Add** names and surnames for your country following the format provided below.
3. **Submit** a Pull Request with your changes.
4. Please **include a reliable source** for the names and surnames you're adding, preferably a public database or a reputable website.

## 📄 Format:

For names (`src/names/zh-cn.ts`):

```typescript
const chineseNames = {
    0: [ // Male names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ],
    1: [ // Female names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ]
}

export default chineseNames;
```

For surnames (`src/surnames/zh-cn.ts`):

```typescript
const saudiSurnames = [ // Add the URL of the surnames source here
    'Surname1', 'Surname2', 'Surname3', ...
];

export default chineseSurnames;
```

## 📌 Important Notes:

- Ensure that the names and surnames you add are common and not specific to a small group.
- 50 names for both males and females, and 50 surnames.
- Organize the names with 10 entries per row.
- Avoid adding names that might be offensive or inappropriate.
- Ensure you're not violating any copyright or data privacy rules.

**Comment by ericmchen15** [comment]
Hello @ozdemirburak , could i please be assigned to this task? Thank you so much.

**Comment by ozdemirburak** [comment]
Sure, actually, there's no need to ask. As long as anyone follows the guidelines, I'm OK with merging any pull request.

**Comment by ericmchen15** [comment]
@ozdemirburak I made two pull requests because I wasn't sure exactly how to merge them, is there a way I can merge the two pull request together so they're in the same pr?

**Comment by ozdemirburak** [comment]
Unfortunately, no. But you can close them, and then squash your commits, then send a new PR. However, it's OK you can, just send two requests.

**Comment by ericmchen15** [comment]
Can check to see if my pull request for Chinese names went through?

**Comment by ozdemirburak** [comment]
Sorry, no.

**Comment by ozdemirburak** [comment]
Please check #37, if you still like to contribute.
