### ISSUE TITLE
Add Finnish Names and Surnames

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/full-name-generator#5]
The repository is missing **Finnish names and surnames**. Follow the guide below to add them.

## 🚀 How to Contribute:

1. **Fork** the repository.
2. **Add** names and surnames for your country following the format provided below.
3. **Submit** a Pull Request with your changes.
4. Please **include a reliable source** for the names and surnames you're adding, preferably a public database or a reputable website.

## 📄 Format:

For names (`src/names/fi.ts`):

```typescript
const finnishNames = {
    0: [ // Male names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ],
    1: [ // Female names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ]
}

export default finnishNames;
```

For surnames (`src/surnames/fi.ts`):

```typescript
const finnishSurnames = [ // Add the URL of the surnames source here
    'Surname1', 'Surname2', 'Surname3', ...
];

export default finnishSurnames;
```

## 📌 Important Notes:

- Ensure that the names and surnames you add are common and not specific to a small group.
- 50 names for both males and females, and 50 surnames.
- Organize the names with 10 entries per row.
- Avoid adding names that might be offensive or inappropriate.
- Ensure you're not violating any copyright or data privacy rules.

**Comment by Anemaygi** [comment]
Hi, can I do it for Brazil? Can you assign me this task? Thank you

**Comment by ozdemirburak** [comment]
Sorry, Brazil is already done.

**Comment by Anemaygi** [comment]
Sorry, i misunderstood. I'm going to do it again with finnish names!
