### ISSUE TITLE
Add French Names and Surnames

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/full-name-generator#6]
The repository is missing **French names and surnames**. Follow the guide below to add them.

## 🚀 How to Contribute:

1. **Fork** the repository.
2. **Add** names and surnames for your country following the format provided below.
3. **Submit** a Pull Request with your changes.
4. Please **include a reliable source** for the names and surnames you're adding, preferably a public database or a reputable website.

## 📄 Format:

For names (`src/names/fr.ts`):

```typescript
const frenchNames = {
    0: [ // Male names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ],
    1: [ // Female names - Add the URL of the names source here
        'Name1', 'Name2', 'Name3', ...
    ]
}

export default frenchNames;
```

For surnames (`src/surnames/fr.ts`):

```typescript
const frenchSurnames = [ // Add the URL of the surnames source here
    'Surname1', 'Surname2', 'Surname3', ...
];

export default frenchSurnames;
```

## 📌 Important Notes:

- Ensure that the names and surnames you add are common and not specific to a small group.
- 50 names for both males and females, and 50 surnames.
- Organize the names with 10 entries per row.
- Avoid adding names that might be offensive or inappropriate.
- Ensure you're not violating any copyright or data privacy rules.

**Comment by belkhoujaons** [comment]
Can i add names from my own DB ? which means no URL provided ? if yes, please assign this to me

**Comment by ozdemirburak** [comment]
Hello @belkhoujaons. You can actually use the list below:

- For names: https://www.insee.fr/fr/statistiques/3532172
- For surnames: https://en.wikipedia.org/wiki/French_name or another one.

**Comment by belkhoujaons** [comment]
I submitted a PR please link it with this issue and review it !
